# Generated by Django 2.0.2 on 2021-04-20 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0002_auto_20210420_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('fechaNacimiento', models.DateField()),
                ('foto', models.CharField(max_length=100)),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Usuario')),
            ],
        ),
    ]
