# Generated by Django 2.0.2 on 2021-04-20 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0003_clientes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clientes',
            new_name='Cliente',
        ),
    ]
