# Generated by Django 2.0.2 on 2021-04-20 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0005_especialista'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('informe', models.TextField()),
                ('realizada', models.BooleanField()),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Cliente')),
                ('idEspecialista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Especialista')),
            ],
        ),
    ]
