# Generated by Django 2.0.2 on 2021-04-20 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0006_cita'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('asunto', models.CharField(max_length=50)),
                ('texto', models.TextField()),
                ('leido', models.BooleanField()),
                ('idEmisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Usuario')),
                ('idReceptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensaje_requests_created', to='nucleo.Usuario')),
            ],
        ),
    ]
